import 'package:flutter/material.dart';
import 'package:i_click/model/user.dart';

class UserProvider with ChangeNotifier {
  final user = [
    Users(
        imageUrl: 'assetc/images/images.png',
        texts: 'Bruno Pham',
        coments: 'liked',
        activity: '"Autumn in my heart"',
        iconn: false,
        like: '',
        imageIcon: true,
        follow: false,
        meseges: false,
        messagetext: '',
        color: false),
    Users(
        imageUrl: 'assetc/images/img1.png',
        texts: 'Bruno Pham',
        coments: 'liked',
        activity: '"Autumn in my heart"',
        iconn: false,
        like: '',
        imageIcon: false,
        follow: true,
        meseges: false,
        messagetext: '',
        color: false),
    Users(
        imageUrl: 'assetc/images/img2.png',
        texts: 'Bruno Pham',
        coments: 'liked',
        activity: '"Autumn in my heart"',
        iconn: false,
        like: '',
        imageIcon: true,
        follow: false,
        meseges: false,
        messagetext: '',
        color: false),
    Users(
        imageUrl: 'assetc/images/img.png',
        texts: 'Bruno Pham',
        coments: 'added',
        activity: '"Autumn in my heart"',
        iconn: false,
        like: '',
        imageIcon: true,
        follow: false,
        meseges: false,
        messagetext: '',
        color: false),
    Users(
        imageUrl: 'assetc/images/img3.png',
        texts: 'Bruno Pham',
        coments: 'added',
        activity: '"Autumn in my heart"',
        iconn: false,
        like: '',
        imageIcon: false,
        follow: true,
        meseges: false,
        messagetext: '',
        color: false),
    Users(
        imageUrl: 'assetc/images/img4.png',
        texts: 'Bruno Pham',
        coments: 'added',
        activity: '"Autumn in my heart"',
        iconn: false,
        like: '',
        imageIcon: true,
        follow: false,
        meseges: false,
        messagetext: '',
        color: false),
  ];
  final message = [
    Users(
        imageUrl: 'assetc/images/Ellipse94.png',
        texts: 'Bruno Pham',
        coments: '',
        activity: '',
        iconn: false,
        like: '',
        imageIcon: false,
        follow: false,
        meseges: true,
        messagetext: 'Hello, I really like your photo...',
        color: true),
    Users(
        imageUrl: 'assetc/images/Ellipse94.png',
        texts: 'Bruno Pham',
        coments: '',
        activity: '',
        iconn: false,
        like: '',
        imageIcon: false,
        follow: false,
        meseges: true,
        messagetext: 'Hello, I really like your photo...',
        color: false),
    Users(
      imageUrl: 'assetc/images/Ellipse94.png',
      texts: 'Bruno Pham',
      coments: '',
      activity: '',
      iconn: false,
      like: '',
      imageIcon: false,
      follow: false,
      meseges: true,
      messagetext: 'Hello, I really like your photo...',
      color: true,
    ),
    Users(
        imageUrl: 'assetc/images/Ellipse94.png',
        texts: 'Bruno Pham',
        coments: '',
        activity: '',
        iconn: false,
        like: '',
        imageIcon: false,
        follow: false,
        meseges: true,
        messagetext: 'Hello, I really like your photo...',
        color: false),
    Users(
        imageUrl: 'assetc/images/Ellipse94.png',
        texts: 'Bruno Pham',
        coments: '',
        activity: '',
        iconn: false,
        like: '',
        imageIcon: false,
        follow: false,
        meseges: true,
        messagetext: 'Hello, I really like your photo...',
        color: true),
    Users(
        imageUrl: 'assetc/images/Ellipse94.png',
        texts: 'Bruno Pham',
        coments: '',
        activity: '',
        iconn: false,
        like: '',
        imageIcon: false,
        follow: false,
        meseges: true,
        messagetext: 'Hello, I really like your photo...',
        color: true),
  ];
}

class SearchProvider with ChangeNotifier {
  final search = [
    Searc(
        searcCartsText: 'PHOTOGRAPHY',
        searcCartsText2: '',
        searcCardsTextTru: true,
        searcCardsTextFals: false,
        searcCardsImages: 'assetc/images/mj2NwYH3wBA.png',
        searcCardsText1Fals:false),
    Searc(
        searcCartsText: '',
        searcCartsText2: 'IILUSTRATION',
        searcCardsTextTru: false,
        searcCardsTextFals: true,
        searcCardsImages: 'assetc/images/CdmpFw9vrX01.png',
        searcCardsText1Fals: false,
        ),
    Searc(
        searcCartsText: 'DESIGN',
        searcCartsText2: '',
        searcCardsTextTru: true,
        searcCardsTextFals: false,
        searcCardsImages: 'assetc/images/CdmpFw9vrX02.png',searcCardsText1Fals: false,),
    Searc(
        searcCartsText: '',
        searcCartsText2: 'MAKING VIDEO',
        searcCardsTextTru: false,
        searcCardsTextFals: true,
        searcCardsImages: 'assetc/images/CdmpFw9vrX03.png',searcCardsText1Fals: false,),

   
  ];
}
class Collect with ChangeNotifier {
  final collect = [
    Searc(
        searcCartsText: 'PHOTOGRAPHY',
        searcCartsText2: '',
        searcCardsTextTru: true,
        searcCardsTextFals: false,
        searcCardsImages: 'assetc/images/mj2NwYH3wBA.png',
        searcCardsText1Fals:false),
    Searc(
        searcCartsText: '',
        searcCartsText2: 'IILUSTRATION',
        searcCardsTextTru: false,
        searcCardsTextFals: true,
        searcCardsImages: 'assetc/images/CdmpFw9vrX01.png',
        searcCardsText1Fals: false,
        ),
    Searc(
        searcCartsText: 'DESIGN',
        searcCartsText2: '',
        searcCardsTextTru: true,
        searcCardsTextFals: false,
        searcCardsImages: 'assetc/images/CdmpFw9vrX02.png',searcCardsText1Fals: false,),
    Searc(
        searcCartsText: '',
        searcCartsText2: 'MAKING VIDEO',
        searcCardsTextTru: false,
        searcCardsTextFals: true,
        searcCardsImages: 'assetc/images/CdmpFw9vrX03.png',searcCardsText1Fals: false,),

   
  ];
}
